Add support for Ravnur Media Services
Ravnur-Inc/Azure-Media-Services-Explorer pull request #1
Opened 2024-01-18 14:36 UTC by vstratovych

## Purpose
This PR adds possibility to connect to RMS instance Ravnur Media Services is one of the possible AMS replacements.
Thanks to identical public API it's possible to use the same SDK and easily switch existing application from AMS to RMS.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[x] User Interface
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What to Check
Verify that the following are valid
* Smoke test that all basic features are working

## Other Information
Detailed documentation about Ravnur Media Services can be found here:
https://github.com/Ravnur-Inc/ams-api-replacement-demo-app

2024-01-29 17:06 UTC, dima-ravnur requested changes

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/AMSClient/AMSClientV3.cs
> +
Lets don't touch things which aren't related to our change

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/DataGrid/DataGridViewStreamingEndpoints.cs
> +                    CDN = ((bool)o.Data.IsCdnEnabled.GetValueOrDefault()) ? StreamingEndpointInformation.ReturnDisplayedProvider(o.Data.CdnProvider) ?? "CDN" : string.Empty,
If this field is missing on our side. I'd suggest to add it to our response and do not change this code

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/DataGrid/DataGridViewStreamingEndpoints.cs
> +                    _MyObservStreamingEndpoints[index].CDN = ((bool)streamingEndpoint.Data.IsCdnEnabled.GetValueOrDefault()) ? StreamingEndpointInformation.ReturnDisplayedProvider(streamingEndpoint.D
same here

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/DataGrid/DataGridViewStreamingEndpoints.cs
> +                                CDN = c.Data.IsCdnEnabled.GetValueOrDefault() ? StreamingEndpointInformation.ReturnDisplayedProvider(c.Data.CdnProvider) ?? "CDN" : string.Empty,
and here

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/Forms-Login/AMSLogin.cs
> +                List<string> properties = new() { "EncryptedADSPClientSecret", "MKIOEncryptedToken", "RavnurEncryptedApiKey" };
Why MKIOEncryptedToken was missing here? Doesn't it work without it?

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/AMSClient/AMSClientV3.cs
> +                armClient = RavnurClientFactory.GetRavnurArmClient(credentialsEntry);
Lets add some comment here that it is a key point where we make AMS SDK work with RMS API

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/Mainform.cs
> -                double nbLiveEvents = leResults.Count();
Don't we break existing functionality for AMS?

2024-01-29 17:06 UTC, dima-ravnur commented on AMSExplorer/Mainform.cs
> +                bool cdnenabled = (bool)se.Data.IsCdnEnabled.GetValueOrDefault();
can we avoid it here as well?

2024-01-30 12:56 UTC, vstratovych commented on AMSExplorer/DataGrid/DataGridViewStreamingEndpoints.cs
> +                    CDN = ((bool)o.Data.IsCdnEnabled.GetValueOrDefault()) ? StreamingEndpointInformation.ReturnDisplayedProvider(o.Data.CdnProvider) ?? "CDN" : string.Empty,
Yes, the value of the field returned from our API is null.

This is totally acceptable according to the nullable value in the model, so this is actually issue in the AMS Explorer code.

However, I agree that we can make change on our side in order to simplify overall complexity of this PR.

2024-01-30 13:41 UTC, vstratovych commented on AMSExplorer/Forms-Login/AMSLogin.cs
> +                List<string> properties = new() { "EncryptedADSPClientSecret", "MKIOEncryptedToken", "RavnurEncryptedApiKey" };
That seems to be a bug introduced when this property was added.

Later in the code there is a comment that describes intention not to export encrypted secrets.
Moreover, the property in CredentialsEntryV4 class contains comment that is very specific about ignoring that property during export.

2024-01-30 14:51 UTC, vstratovych commented on AMSExplorer/Mainform.cs
> -                double nbLiveEvents = leResults.Count();
No, I don't think so.
We just made sure that live events API isn't called for RMS.
For AMS everything should work just as it was before.

2024-01-30 14:52 UTC, vstratovych commented on AMSExplorer/Mainform.cs
> +                bool cdnenabled = (bool)se.Data.IsCdnEnabled.GetValueOrDefault();
I'm going to revert this change and do fix in RMS API instead.

2024-01-30 15:02 UTC, dima-ravnur approved these changes

2024-02-26 13:57 UTC, merged